# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: rfcontrol.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'rfcontrol.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0frfcontrol.proto\x12\trfcontrol\">\n\x08RFConfig\x12\x11\n\tfrequency\x18\x01 \x01(\t\x12\x0c\n\x04gain\x18\x02 \x01(\t\x12\x11\n\tdevice_id\x18\x03 \x01(\t\"-\n\nRFResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\"(\n\x13\x44\x65viceStatusRequest\x12\x11\n\tdevice_id\x18\x01 \x01(\t\"4\n\x11\x44\x65viceStatusReply\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\"G\n\x0f\x44\x65layedResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12$\n\x07request\x18\x02 \x03(\x0b\x32\x13.rfcontrol.RFConfig2\xaf\x02\n\tRFControl\x12;\n\rSetRFSettings\x12\x13.rfcontrol.RFConfig\x1a\x15.rfcontrol.RFResponse\x12U\n\x13MonitorDeviceStatus\x12\x1e.rfcontrol.DeviceStatusRequest\x1a\x1c.rfcontrol.DeviceStatusReply0\x01\x12\x46\n\x11\x42ulkSetRFSettings\x12\x13.rfcontrol.RFConfig\x1a\x1a.rfcontrol.DelayedResponse(\x01\x12\x46\n\x14InteractingRFControl\x12\x13.rfcontrol.RFConfig\x1a\x15.rfcontrol.RFResponse(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rfcontrol_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RFCONFIG']._serialized_start=30
  _globals['_RFCONFIG']._serialized_end=92
  _globals['_RFRESPONSE']._serialized_start=94
  _globals['_RFRESPONSE']._serialized_end=139
  _globals['_DEVICESTATUSREQUEST']._serialized_start=141
  _globals['_DEVICESTATUSREQUEST']._serialized_end=181
  _globals['_DEVICESTATUSREPLY']._serialized_start=183
  _globals['_DEVICESTATUSREPLY']._serialized_end=235
  _globals['_DELAYEDRESPONSE']._serialized_start=237
  _globals['_DELAYEDRESPONSE']._serialized_end=308
  _globals['_RFCONTROL']._serialized_start=311
  _globals['_RFCONTROL']._serialized_end=614
# @@protoc_insertion_point(module_scope)
